{
 "title": "UPF Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "upfs", "label": "UPFs", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "$upfs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "upfs" },
  {
   "title": "Current Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_latency_ns{namespace=\"$upfs\",quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_latency_ns{namespace=\"$upfs\",quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_jitter_ns{namespace=\"$upfs\",quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_jitter_ns{namespace=\"$upfs\",quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(upf_dropped_count{namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Packet drops per second"
    }
   ]
  },
  { "title": "$upfs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Current Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_latency_ns{namespace=\"$upfs\",quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_latency_ns{namespace=\"$upfs\",quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_jitter_ns{namespace=\"$upfs\",quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_jitter_ns{namespace=\"$upfs\",quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(upf_dropped_count{namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Packet drops per second"
    }
   ]
  },
  { "title": "$upfs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Current Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 27 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_latency_ns{namespace=\"$upfs\",quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_latency_ns{namespace=\"$upfs\",quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\",namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_jitter_ns{namespace=\"$upfs\",quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_jitter_ns{namespace=\"$upfs\",quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 35 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(upf_dropped_count{namespace=\"$upfs\"}[2m]))",
     "legendFormat": "Packet drops per second"
    }
   ]
  }
 ]
}