{
 "title": "Subscriber Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "eNodeB Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mme_number_of_enb_attached{enb_state=\"Active\", enbname=~\".+\"}) by (enbname,enbid)",
     "legendFormat": "{{ enbname }}"
    }
   ]
  },
  {
   "title": "Subscriber Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(subscribers_info{imsi=~\".+\"}) by (imsi)"
    }
   ]
  },
  {
   "title": "UE Activation over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Active" }
   ],
   "targets": [
    {
     "expr": "clamp_max(sum(subscribers_info{imsi=~\".+\"}) by (imsi), 1)",
     "legendFormat": "{{ imsi }}"
    }
   ]
  },
  {
   "title": "Active subscribers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(subscribers_info{imsi=~\".+\"} > 0) by (imsi))"
    }
   ]
  }
 ]
}